name: hw-bits
version: '0.7.0.5'
synopsis: Bit manipulation
description: Please see README.md
category: Data, Bit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-bits
homepage: http://github.com/haskell-works/hw-bits#readme
tested-with: GHC == 8.6.3, GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2
extra-source-files:
- README.md
dependencies:
- base        >= 4.8        && < 5
- vector      >= 0.12       && < 0.13
library:
  source-dirs: src
  dependencies:
  - bytestring        >= 0.9        && < 0.11
  - hw-int            >= 0.0.0.1    && < 0.1
  - hw-prim           >= 0.4.0.3    && < 0.7
  - hw-string-parse   >= 0.0.0.1    && < 0.1
  - safe
  when:
  - condition: flag(sse42)
    then:
      ghc-options:
      - -Wall
      - -O2
      - -msse4.2
    else:
      ghc-options:
      - -Wall
      - -O2
tests:
  hw-bits-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bytestring              >= 0.9        && < 0.11
    - hedgehog                >= 0.5        && < 0.7
    - hspec                   >= 2.4        && < 3
    - hw-hspec-hedgehog       >= 0.1.0.4    && < 0.2
    - hw-bits
    - hw-prim                 >= 0.4.0.3    && < 0.7
    - QuickCheck              >= 2.10       && < 2.12
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    dependencies:
    - criterion >= 1.2        && < 1.6
    - hw-bits
    - hw-prim   >= 0.4.0.0    && < 0.7
    when:
    - condition: flag(sse42)
      then:
        ghc-options:
        - -Wall
        - -O2
        - -msse4.2
      else:
        ghc-options:
        - -Wall
        - -O2
flags:
  sse42:
    description: Enable SSE 4.2 optimisations.
    manual: false
    default: true
stability: Experimental
